name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build Vue.js app [frontend]
        run: npm run build
        working-directory: frontend

      #- name: Install backend dependencies
      #  run: npm install
      #  working-directory: backend

      #- name: Build Vue.js app [backend]
      #  run: npm run build
      #  working-directory: backend

      #- name: Install backend dependencies
      #  run: composer install
      #  working-directory: backend


      - name: Deploy frontend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_FRONT_USER }}
          password: ${{ secrets.FTP_FRONT_PASSWORD }}
          local-dir: ./frontend/dist/
          server-dir: /

      #- name: Deploy backend
      #  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #  with:
      #    server: ${{ secrets.FTP_SERVER }}
      #    username: ${{ secrets.FTP_BACK_USER }}
      #    password: ${{ secrets.FTP_BACK_PASSWORD }}
      #    local-dir: ./backend/
      #    remote-dir: /
